#!/usr/bin/env node
// Writes the "Linked to Written as Spoken" block into every routed sub-skill, from
// references/routing-map.json, so the back-links never drift from the graph.
// Usage: node sync-links.mjs          rewrite the blocks
//        node sync-links.mjs --check  exit 1 if any block is missing or stale

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const map = JSON.parse(readFileSync(join(root, 'references', 'routing-map.json'), 'utf8'));

export const START = '<!-- written-as-spoken:links start (generated by scripts/sync-links.mjs, do not edit by hand) -->';
export const END = '<!-- written-as-spoken:links end -->';

const code = (s) => `\`${s}\``;

export function renderBlock(id) {
  const node = map.nodes[id];
  const up = relative(dirname(join(root, node.path)), root) || '.';
  const ref = (p) => `${up}/${p}`;

  const routes = [];
  for (const [intentId, intent] of Object.entries(map.intents)) {
    const i = intent.chain.indexOf(id);
    if (i === -1) continue;
    const prev = intent.chain[i - 1];
    const next = intent.chain[i + 1];
    const from = prev ? `after ${code(prev)}` : 'first step';
    const to = next ? `hands off to ${code(next)}` : `returns to ${code(map.front_door)}`;
    routes.push(`${code(intentId)} (${intent.label}): ${from}, ${to}`);
  }
  for (const [modId, m] of Object.entries(map.modifiers)) {
    if (m.node === id) routes.push(`modifier ${code(modId)}: inserted into any route when the request carries that signal`);
  }

  const feedback = [];
  for (const [group, edges] of Object.entries(map.feedback)) {
    for (const [rule, edge] of Object.entries(edges)) {
      if (edge.owner === id) feedback.push(`${group} ${code(rule)}: ${edge.move}`);
    }
  }
  const overrides = map.overrides.filter((o) => o.node === id).map((o) => o.rule);

  const lines = [
    START,
    '',
    '## Linked to Written as Spoken',
    '',
    `This skill is a node in the Written as Spoken suite. The front door is ${code(map.front_door)} (${code(ref('SKILL.md'))}), and the graph lives in ${code(ref('references/routing-map.json'))}.`,
    '',
    `When a request reaches this skill through ${code(map.front_door)}, Mamdouh's voice rules in ${code(ref('references/voice-dna.md'))} and ${code(ref('references/anti-slop.md'))} outrank this skill's own style defaults, the house profile is active, and facts come only from the user or from ${code('story-researcher')}.`,
    '',
  ];
  if (routes.length) lines.push('Routes that pass through here:', '', ...routes.map((r) => `- ${r}`), '');
  if (feedback.length) lines.push('Sent here by the feedback loop:', '', ...feedback.map((f) => `- ${f}`), '');
  if (overrides.length) lines.push('Overrides inside this suite:', '', ...overrides.map((o) => `- ${o}`), '');
  lines.push(
    `Hand your output to the next node in the route. When this skill is the last node, return the result to ${code(map.front_door)} so the draft goes through ${code(ref('scripts/lint.mjs'))} before the user sees it. When this skill is called directly, outside the suite, ignore this block.`,
    '',
    END,
  );
  return lines.join('\n');
}

export function applyBlock(body, block) {
  const s = body.indexOf(START);
  const e = body.indexOf(END);
  if (s !== -1 && e !== -1) return body.slice(0, s) + block + body.slice(e + END.length);
  return body.replace(/\s*$/, '\n\n') + block + '\n';
}

export const linkedNodes = () =>
  Object.entries(map.nodes)
    .filter(([id, n]) => n.kind === 'skill' && id !== map.front_door)
    .map(([id]) => id);

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const id of linkedNodes()) {
    const file = join(root, map.nodes[id].path);
    const body = readFileSync(file, 'utf8');
    const next = applyBlock(body, renderBlock(id));
    if (next === body) continue;
    stale++;
    if (check) console.log(`STALE ${map.nodes[id].path}`);
    else {
      writeFileSync(file, next);
      console.log(`wrote ${map.nodes[id].path}`);
    }
  }
  if (check) console.log(stale ? `STALE: ${stale} block(s), run node scripts/sync-links.mjs` : 'PASS: all link blocks in sync');
  else console.log(`${stale} file(s) updated`);
  process.exit(check && stale ? 1 : 0);
}
